[package]
name = "libsignal-service-actix"
version = "0.1.0"
authors = ["Ruben De Smet <ruben.de.smet@rubdos.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsignal-service = { path = "../libsignal-service" }
libsignal-protocol = { git = "https://github.com/Michael-F-Bryan/libsignal-protocol-rs" }

awc = { version = "2.0.0", features=["rustls"] }
actix = "0.10.0"
actix-http = "2.1.0"
actix-rt = "1.1"
actix-multipart-rfc7578 = {version = "0.3.0-rc", git="https://github.com/rubdos/rust-multipart-rfc7578.git", branch="actix-2"} # Not an "official" actix project
serde_json = "1.0"
futures = "0.3"
bytes = "0.5"
rustls = "0.18"
url = "2.1"
serde = "1.0"
log = "0.4.8"

failure = "0.1.5"
thiserror = "1.0"
async-trait = "0.1.30"
base64 = "0.13"

[dev-dependencies]
env_logger = "0.8"
image = { version = "0.23", default-features = false, features = ["png"] }
opener = "0.4"
qrcode = "0.12"
rand = "0.7"
structopt = "0.3"
tokio = { version = "0.2", features=["macros"] }
