[package]
name = "libsignal-service"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>", "Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"
license = "GPLv3"
readme = "../README.md"

[dependencies]
libsignal-protocol = { git = "https://github.com/Michael-F-Bryan/libsignal-protocol-rs" }
async-trait = "0.1.30"
url = { version = "2.1.1", features = ["serde"] }
base64 = "0.13"
bytes = "0.5"
chrono = "0.4"
futures = "0.3"
pin-project = "1.0"
thiserror = "1.0"
serde = {version = "1.0", features=["derive"]}
prost = "0.6"
http = "0.2.1"
log = "0.4.8"

sha2 = "0.9.0"
hmac = "0.10.0"
aes = "0.6.0"
aes-gcm = "0.8.0"
block-modes = "0.7.0"
rand = "0.7.0"

[build-dependencies]
prost-build = "0.6"
